export enum EmployeeRole {
  ADMIN = "ADMIN",
  EMPLOYEE = "EMPLOYEE",
}

export enum JobStatus {
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  UNDER_REVIEW = "UNDER_REVIEW",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  COMPLETED = "COMPLETED",
}

export enum ReviewAction {
  SUBMITTED = "SUBMITTED",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  APPROVED = "APPROVED",
}

export enum NotificationType {
  JOB_ASSIGNED = "JOB_ASSIGNED",
  JOB_SUBMITTED = "JOB_SUBMITTED",
  JOB_APPROVED = "JOB_APPROVED",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
}
